### ISSUE TITLE
Adding model to batchSearchableModels

### ISSUE THREAD

**Issue by keithbrink** [optimistdigital/laravel-scout-batch-searchable#1]
Hi there, thanks for this package, needed this feature to solve rate limits with my elasticsearch host.

Just FYI, I had to add this line to my AppServiceProvider boot method:

`ScoutBatchSearchableServiceProvider::$batchSearchableModels[] = Item::class;`

In order to get the scheduled command working.

Let me know if I missed something!

**Comment by Tarpsvo** [comment]
That's weird. It should be automatically added when the BatchSearchable trait boots (or more specifically, when the Searchable trait boots inside BatchSearchable trait). Maybe you have included both Searchable and BatchSearchable traits?

https://github.com/optimistdigital/laravel-scout-batch-searchable/blob/b672dfe6a90215258cb19a737ad89cea3ed12751/src/BatchSearchable.php#L29

**Comment by keithbrink** [comment]
Nope, I added some debugging and that `registerSearchableMacros` function doesn't run unless I initialize the model (even just running `new Item` from the AppServiceProvider works). My guess is that artisan commands don't boot the models.

**Comment by Tarpsvo** [comment]
Ah crap, okay. I guess I need to make the model registration into a manual action then after all. It does make sense that it does not run unless the model is booted somewhere.

**Comment by Tarpsvo** [comment]
Heya @keithbrink! I think I managed to fix this without adding an explicit configuration option.

Whenever an item is added to the batch queue, I save the class name to an array in cache with the key `BATCH_SEARCHABLE_QUEUED_MODELS` (deduped unique of course). This should work perfectly and no explicit configuration is no longer needed.

NB! The `ServiceProvider::$batchSearchableModels[]` static array no longer exists, so when you update, you have to remove this part from your app as well. This was added in version 1.1.0.

**Comment by keithbrink** [comment]
@Tarpsvo Brilliant! Thanks so much.
